### PR TITLE
Make GNOME configuration more declarative

### PR DESCRIPTION
**Pull request by greysoh**
# Summary
This makes the GNOME Nix configuration more reproducible, by declaring the GNOME configuration directly.

### CODE REVIEW

**Comment by greysoh** [comment]
Just noticed custom cursors still don't work

**Comment by greysoh** [comment]
Fixed

**Comment by greysoh** [comment]
Nevermind, the cursor isn't fixed. I had thought I fixed it, but it isn't picking up on it still.

**Comment by kyolinedev** [comment]
ty lgtm

**Pull request merged**
